module.exports = {
	add: require("./command_add"),
	build: require("./command_build"),
	build_server: require("./command_build_server"),
	clean: require("./command_clean"),
	msbuild: require("./command_msbuild"),
	new: require("./command_new"),
	nuget: require("./command_nuget"),
	pack: require("./command_pack"),
	publish: require("./command_publish"),
	remove: require("./command_remove"),
	restore: require("./command_restore"),
	run: require("./command_run"),
	sln: require("./command_sln"),
	store: require("./command_store"),
	test: require("./command_test"),
	tool: require("./command_tool"),
	vstest: require("./command_vstest"),
	dev_certs: require("./command_dev_certs"),
	fsi: require("./command_fsi"),
	sql_cache: require("./command_sql_cache"),
	user_secrets: require("./command_user_secrets")
};
